### ISSUE TITLE
Guests can see rooms available

### ISSUE THREAD

**Issue by bheim6** [kctrlv/restful_stay#39]
As a Guest

When I visit "/"
I expect to see a list of cities with available listings
I expect to see a field to select the dates of my trip
When I fill in start and end date
And I click on a city link

I expect my path to be "/listings?city=City_name?start_date=day?end_date=day"
I expect to see a list of listings available in this city for the dates selected

When I click on "View Listing" for a listing
I expect my path to be "/listings?city=City_name/:listing_id"
I expect to see the name of the listing
I expect to see an image(s) associated with the listing
I expect to see a description of the listing
I expect to see a link to "Book this Listing"

When I click on "Book this Listing"

I expect to see an error(flash) message "Must be registered to book a listing"
I expect to be redirected to "/signup"

**Comment by kctrlv** [comment]
# As a visitor
    # Given that a particular city has listings
    # When I visit "/"
    # I expect to see a list of cities with listings
    # And I click on Colorado Springs
    # I expect my path to be "/cities/colorado_springs"
    # I expect to see a list of listings available in this city

**Comment by kctrlv** [comment]
The rest of the test is for traveler can book room; visitor cannot book a room, this is a separate waffle card. this card is done
