### ISSUE TITLE
visitor can Sign up

### ISSUE THREAD

**Issue by bheim6** [kctrlv/restful_stay#6]
As a visitor
When I visit '/'
and I click link to "Sign Up"
I expect current path to be '/sign_up'
I expect to see a form

and I fill in  "First Name" with "Chad"
and I fill in "Last Name" with  "Clancey"
and I fill in "Email Address" with "cc007@gmail.com"
and I fill in "Password" with "clanceytime"
and I fill in "Birthdate" with "07/07/1907"
and I fill in phone number with "5551234567"
and I click "Submit"

then I should expect to be on '/confirmation'
and my account should be created but inactive
And I should see instructions to enter my confirmation code
And I should have received a text message with a confirmation code

When I enter the confirmation code
And I click "Submit"
Then I should be redirected to "/dashboard"
And I should see a "Chad" in the navbar

**Comment by rsbarbo** [comment]
add phone number and have tool tip for the reason why we are requesting their phone number.

**Comment by rsbarbo** [comment]
Brainstorm about how we gonna do the second authentication.
