### ISSUE TITLE
Admin can alter messages

### ISSUE THREAD

**Issue by NateAnderson1780** [kctrlv/restful_stay#75]

**Comment by rsbarbo** [comment]
@NateAnderson1780 did you mean to open this issue or was it done by mistake? Let us know. Thanks

**Comment by NateAnderson1780** [comment]
@rsbarbo haha my bad. My blog was about project management tools and there were a few issues in our restful stay left so I used that for one of my screenshots as well as adding one which ended showing up here. Sorry about that.
