### ISSUE TITLE
any visitor/user can visit the "About" page

### ISSUE THREAD

**Issue by bheim6** [kctrlv/restful_stay#9]
as a visitor (logged in or not)
when I click link "About"

I expect my current path to be  '/about'

and I should see "Created by: David Davydov, Nate Anderson, Raphael Barbo, and Brian Heim"

**Comment by rsbarbo** [comment]
This test is passing now, however, we need to create the log in page before I can cover 100% of the edge cases, I will leave this card as WOP so we know that we need to go back and adjust the test for user can see visit about page (scenario). Rapha Barbo
